[package]
name = "desktop-shell"
version = "0.1.14"
edition.workspace = true
license.workspace = true
repository.workspace = true

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
desktop-core = { path = "../../../crates/desktop-core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3"
